train:
  seed: 42
  max_iter: 5000
  batch_size: 128
  log_freq: 50
  val_freq: 500
  save_freq: 5000
  max_grad_norm: 100.
  optimizer:
    type: adam
    lr: 3.e-4
    weight_decay: 0.
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.5
    patience: 10
    min_lr: 1.e-5

datasets:
  root: data/ala

model:
  type: schnet
  hidden_channels: 128
  num_filters: 128
  num_interactions: 6
  num_gaussians: 50
  cutoff: 3.
